FROM public.ecr.aws/docker/library/node:20-slim AS builder

WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@10.32.1 --activate
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
RUN pnpm run db:generate

COPY tsconfig.json ./
COPY src ./src
RUN pnpm run build

FROM public.ecr.aws/docker/library/node:20-slim AS runner

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.1 /lambda-adapter /opt/extensions/lambda-adapter

ENV NODE_ENV=production
ENV PORT=3000
ENV AWS_LWA_PORT=3000

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY prisma ./prisma

EXPOSE 3000

CMD ["node", "dist/server.js"]
